### ISSUE TITLE
SPI_Int.h Comments

### ISSUE THREAD

**Issue by Mohamed-Hawas** [V2ADAS/Embeddedians#30]
You  have to write a comments for APIs of SPI driver to help the whole team member to work without forcing us to memorize  how it work . 
### comment template 

1. List of APIs
2. API Comment 
   2.1 API function description 
   2.2 API function input (if it need any macros you should write it)
   2.3 API function output

Attached template to make our work unified
[MUSART_Interface.h](https://github.com/V2ADAS/Embeddedians/blob/main/Src/MCAL/MUART/MUSART_Interface.h)

**Comment by OmarWael22** [comment]
Done
