### ISSUE TITLE
Car Control enhance 

### ISSUE THREAD

**Issue by Mohamed-Hawas** [V2ADAS/Embeddedians#54]
in this part you make two func . but we need one func like "CAR_CONTROL(Dir , Dist , speed , degree)"
### attention pls : 
 in this func if u start with move func and then serco_degree , the car will wait to finish motor_move and then it will steer .
 So u have to start with steering func .
### example
![image](https://github.com/V2ADAS/Embeddedians/assets/57467484/1a7bb901-119c-4318-a401-788b082c76d3)

the code above is the scenario which i have sent it .

**Comment by M0hamed-Eid** [comment]
Done
