### ISSUE TITLE
Scanning using distance

### ISSUE THREAD

**Issue by Mohamed-Hawas** [V2ADAS/Embeddedians#63]
### Problem
Unfortunately , It is so difficult to scan using time delay or speed because the speed will vary with the surface and there is some mechanical errors in gears that make the velocity highly varying  and it will be so difficult to control it .
### Solution
I wish that car can take a reading from the ultra sonic every 1cm and I have already a feedback tell me the distance which car travelled , **Encoder**
### Constrains
1. Encoder giveback a 1024 pulse per revolution 
2. Wheel Area =  26.4 cm 
3. Each 38.7~38 pulse map to 1cm , pulses must be integer values so floor(38.7)  
### Must be known 
In motor driver the variable encoder_pulses has the number of pulses achieved , so you should use it

**Comment by V2ADAS** [comment]
Implementation completed. Ready for testing in a real-world scenario.
